<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SettingsManager</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="FluxDB">
      <HintPath>fluxioElrosk/fluxioElrosk/FluxDB.dll</HintPath>
    </Reference>
    <Reference Include="SimpleLogger">
      <HintPath>fluxioElrosk/fluxioElrosk/SimpleLogger.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>