<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>True</UseWindowsForms>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Scanix4\Scanix4.csproj" />
    <ProjectReference Include="..\SnapNetClient\SnapNetClient.csproj" />
    <ProjectReference Include="..\Server\Server.csproj" />
    <ProjectReference Include="..\UI2\UI2.csproj" />
  </ItemGroup>
</Project>
