<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>InputInterceptor</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="InputInterceptorNS.Resources.install-interception.exe" />
    <None Remove="InputInterceptorNS.Resources.interception_x64.dll" />
    <None Remove="InputInterceptorNS.Resources.interception_x86.dll" />
    <EmbeddedResource Include="InputInterceptorNS.Resources.install-interception.exe" LogicalName="InputInterceptorNS.Resources.install-interception.exe" />
    <EmbeddedResource Include="InputInterceptorNS.Resources.interception_x64.dll" LogicalName="InputInterceptorNS.Resources.interception_x64.dll" />
    <EmbeddedResource Include="InputInterceptorNS.Resources.interception_x86.dll" LogicalName="InputInterceptorNS.Resources.interception_x86.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>
</Project>