<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Scanix4</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20241108" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.10.0.20241108" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20241108" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.3" />
    <PackageReference Include="System.Windows.Extensions" Version="9.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FluxDB\FluxDB.csproj" />
    <ProjectReference Include="..\InputInterceptor\InputInterceptor.csproj" />
    <ProjectReference Include="..\InputManager\InputManager.csproj" />
    <ProjectReference Include="..\SettingsManager\SettingsManager.csproj" />
    <ProjectReference Include="..\SimpleLogger\SimpleLogger.csproj" />
    <ProjectReference Include="..\SnapNetClient\SnapNetClient.csproj" />
  </ItemGroup>
</Project>
