<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>UI2</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FluxDB\FluxDB.csproj" />
    <ProjectReference Include="..\InputInterceptor\InputInterceptor.csproj" />
    <ProjectReference Include="..\InputManager\InputManager.csproj" />
    <ProjectReference Include="..\Scanix4\Scanix4.csproj" />
    <ProjectReference Include="..\SettingsManager\SettingsManager.csproj" />
    <ProjectReference Include="..\SimpleLogger\SimpleLogger.csproj" />
    <ProjectReference Include="..\SnapNetClient\SnapNetClient.csproj" />
  </ItemGroup>
</Project>
