<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>UI2</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="SettingsManager">
      <HintPath>fluxioElrosk/fluxioElrosk/SettingsManager.dll</HintPath>
    </Reference>
    <Reference Include="InputManager">
      <HintPath>fluxioElrosk/fluxioElrosk/InputManager.dll</HintPath>
    </Reference>
    <Reference Include="SimpleLogger">
      <HintPath>fluxioElrosk/fluxioElrosk/SimpleLogger.dll</HintPath>
    </Reference>
    <Reference Include="InputInterceptor">
      <HintPath>fluxioElrosk/fluxioElrosk/InputInterceptor.dll</HintPath>
    </Reference>
    <Reference Include="FluxDB">
      <HintPath>fluxioElrosk/fluxioElrosk/FluxDB.dll</HintPath>
    </Reference>
    <Reference Include="Scanix4">
      <HintPath>fluxioElrosk/fluxioElrosk/Scanix4.dll</HintPath>
    </Reference>
    <Reference Include="SnapNetClient">
      <HintPath>fluxioElrosk/fluxioElrosk/SnapNetClient.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.SQLite">
      <HintPath>fluxioElrosk/fluxioElrosk/System.Data.SQLite.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>